### ISSUE TITLE
Make `lang` support arrays

### ISSUE THREAD

**Issue by kwaa** [importantimport/fff#11]
Compatible with [Lume Multilanguage Plugin](https://lume.land/plugins/multilanguage/#multilanguage-pages-from-a-single-file)

Should be implemented in FFF 0.6

```yaml
lang:
  - en
  - zh
  - ja
# or
lang: [en, zh, ja]
```
