### ISSUE TITLE
Add `authors` variable

### ISSUE THREAD

**Issue by kwaa** [importantimport/fff#3]
The target is the equivalent of JSON Feed's `authors`.

## Type

> Note: Backward compatibility is not required, so only arrays of objects are accepted.

```ts
type Author = {
  /** the author’s name. */
  name: string
  /** the URL of a site owned by the author. */
  url?: string
  /** the URL for an image for the author. */
  avatar?: string
}

/**
 * FFF Flavored Frontmatter
 * Version 0.2.0-draft
 */
type FFFFlavoredFrontmatter = {
  ...
  authors?: Author[]
  ...
}
```

## Usage

```yaml
authors:
  - name: John Doe
    url: https://example.com/john
    avatar: https://example.com/john.avif
  - name: Jane Doe
    url: https://example.com/jane
    avatar: https://example.com/jane.avif
```
